version: "3.8"
services:
  app:
    container_name: nest-mvcs-rest-crud
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    command: npm run start:dev
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 5445
      MONGODB_URI: mongodb+srv://admin:admin@development.9u7aknr.mongodb.net/petsdb?retryWrites=true&w=majority
    ports:
      - 4000:5445
